/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, copyDefault, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && (copyDefault || key !== "default"))
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toCommonJS = /* @__PURE__ */ ((cache) => {
  return (module2, temp) => {
    return cache && cache.get(module2) || (temp = __reExport(__markAsModule({}), module2, 1), cache && cache.set(module2, temp), temp);
  };
})(typeof WeakMap !== "undefined" ? /* @__PURE__ */ new WeakMap() : 0);

// auth/oauth.ts
var oauth_exports = {};
__export(oauth_exports, {
  OAuthManager: () => OAuthManager
});
var import_obsidian, SCOPES, REDIRECT_URI, OAuthManager;
var init_oauth = __esm({
  "auth/oauth.ts"() {
    import_obsidian = require("obsidian");
    SCOPES = "https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.metadata.readonly openid email";
    REDIRECT_URI = "https://obsidian.md";
    OAuthManager = class {
      static async generateCodeVerifier() {
        const array = new Uint8Array(32);
        window.crypto.getRandomValues(array);
        return btoa(String.fromCharCode(...array)).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
      }
      static async generateCodeChallenge(verifier) {
        const encoder = new TextEncoder();
        const data = encoder.encode(verifier);
        const digest = await window.crypto.subtle.digest("SHA-256", data);
        return btoa(String.fromCharCode(...new Uint8Array(digest))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
      }
      static async getAuthUrl(clientId, codeChallenge) {
        return `https://accounts.google.com/o/oauth2/v2/auth?client_id=${clientId}&redirect_uri=${encodeURIComponent(REDIRECT_URI)}&response_type=code&scope=${encodeURIComponent(SCOPES)}&code_challenge=${codeChallenge}&code_challenge_method=S256&access_type=offline&prompt=consent`;
      }
      static async exchangeCodeForToken(code, codeVerifier, clientId, clientSecret) {
        const response = await (0, import_obsidian.requestUrl)({
          url: "https://oauth2.googleapis.com/token",
          method: "POST",
          headers: { "Content-Type": "application/x-www-form-urlencoded" },
          body: new URLSearchParams({
            client_id: clientId,
            client_secret: clientSecret,
            code,
            code_verifier: codeVerifier,
            redirect_uri: REDIRECT_URI,
            grant_type: "authorization_code"
          }).toString()
        });
        return response.json;
      }
      static async refreshToken(refreshToken, clientId, clientSecret) {
        const response = await (0, import_obsidian.requestUrl)({
          url: "https://oauth2.googleapis.com/token",
          method: "POST",
          headers: { "Content-Type": "application/x-www-form-urlencoded" },
          body: new URLSearchParams({
            client_id: clientId,
            client_secret: clientSecret,
            refresh_token: refreshToken,
            grant_type: "refresh_token"
          }).toString()
        });
        return response.json;
      }
    };
  }
});

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GoogleDriveSyncPlugin
});
var import_obsidian7 = require("obsidian");

// sync/state.ts
var StateManager = class {
  constructor(plugin) {
    this.state = {};
    this.plugin = plugin;
  }
  async load() {
    const data = await this.plugin.app.vault.adapter.read(".obsidian/gdrive-sync.json").catch(() => "{}");
    this.state = JSON.parse(data);
  }
  async save() {
    await this.plugin.app.vault.adapter.write(".obsidian/gdrive-sync.json", JSON.stringify(this.state, null, 2));
  }
  get(path) {
    return this.state[path];
  }
  set(path, entry) {
    this.state[path] = entry;
  }
  remove(path) {
    delete this.state[path];
  }
};

// sync/gdrive.ts
var import_obsidian2 = require("obsidian");
var GoogleDriveClient = class {
  constructor(accessToken, onTokenRefresh, refreshParams) {
    this.accessToken = accessToken;
    this.onTokenRefresh = onTokenRefresh;
    this.refreshParams = refreshParams;
  }
  async request(options, retry = true) {
    options.headers = {
      ...options.headers,
      "Authorization": `Bearer ${this.accessToken}`
    };
    let response;
    try {
      response = await (0, import_obsidian2.requestUrl)(options);
    } catch (error) {
      const status = error instanceof Object && "status" in error ? error.status : void 0;
      if (status === 401 && retry && this.refreshParams && this.onTokenRefresh) {
        return await this.handleRefresh(options);
      }
      throw error;
    }
    if (response.status === 401 && retry && this.refreshParams && this.onTokenRefresh) {
      return await this.handleRefresh(options);
    }
    if (response.status >= 400) {
      let message = response.text || `Status ${response.status}`;
      try {
        const json = JSON.parse(response.text);
        if (json.error && json.error.message) {
          message = json.error.message;
        }
      } catch (e) {
      }
      const error = new Error(`Google Drive API Error: ${message}`);
      error.status = response.status;
      throw error;
    }
    return response;
  }
  async handleRefresh(options) {
    console.log("Access token expired. Attempting refresh...");
    try {
      const { OAuthManager: OAuthManager2 } = await Promise.resolve().then(() => (init_oauth(), oauth_exports));
      if (!this.refreshParams)
        throw new Error("No refresh parameters");
      const tokens = await OAuthManager2.refreshToken(this.refreshParams.refreshToken, this.refreshParams.clientId, this.refreshParams.clientSecret);
      this.accessToken = tokens.access_token;
      if (this.onTokenRefresh) {
        await this.onTokenRefresh(tokens);
      }
      return this.request(options, false);
    } catch (refreshError) {
      console.error("Token refresh failed", refreshError);
      throw new Error("Session expired. Please log in again.");
    }
  }
  async listFiles(folderId) {
    let files = [];
    let pageToken;
    do {
      const q = `'${folderId}' in parents and trashed = false`;
      const url = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=nextPageToken,files(id,name,mimeType,modifiedTime,md5Checksum,size)${pageToken ? `&pageToken=${pageToken}` : ""}`;
      const response = await this.request({ url, method: "GET" });
      files = files.concat(response.json.files || []);
      pageToken = response.json.nextPageToken;
    } while (pageToken);
    return files;
  }
  async downloadFile(fileId) {
    const url = `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`;
    const response = await this.request({ url, method: "GET" });
    return response.arrayBuffer;
  }
  async listFolders(parentId = "root") {
    let files = [];
    let pageToken;
    do {
      const q = `'${parentId}' in parents and mimeType = 'application/vnd.google-apps.folder' and trashed = false`;
      const url = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=nextPageToken,files(id,name,mimeType,modifiedTime)${pageToken ? `&pageToken=${pageToken}` : ""}`;
      const response = await this.request({ url, method: "GET" });
      files = files.concat(response.json.files || []);
      pageToken = response.json.nextPageToken;
    } while (pageToken);
    return files;
  }
  async createFolder(name, parentId) {
    const metadata = {
      name,
      mimeType: "application/vnd.google-apps.folder",
      parents: parentId ? [parentId] : []
    };
    const url = "https://www.googleapis.com/drive/v3/files";
    const response = await this.request({
      url,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(metadata)
    });
    return response.json;
  }
  async uploadFile(name, folderId, content, mimeType = "text/markdown") {
    const metadata = {
      name,
      parents: [folderId],
      mimeType
    };
    const initUrl = "https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable";
    const initResponse = await this.request({
      url: initUrl,
      method: "POST",
      headers: {
        "Content-Type": "application/json; charset=UTF-8",
        "X-Upload-Content-Type": mimeType
      },
      body: JSON.stringify(metadata)
    });
    const uploadUrl = initResponse.headers["location"] || initResponse.headers["Location"];
    if (!uploadUrl)
      throw new Error("Failed to get resumable upload URL");
    const uploadResponse = await this.request({
      url: uploadUrl,
      method: "PUT",
      headers: {
        "Content-Type": mimeType
      },
      body: content
    });
    return uploadResponse.json;
  }
  async updateFile(fileId, content, mimeType = "text/markdown") {
    const initUrl = `https://www.googleapis.com/upload/drive/v3/files/${fileId}?uploadType=resumable`;
    const initResponse = await this.request({
      url: initUrl,
      method: "PATCH",
      headers: {
        "Content-Type": "application/json; charset=UTF-8",
        "X-Upload-Content-Type": mimeType
      },
      body: JSON.stringify({})
    });
    const uploadUrl = initResponse.headers["location"] || initResponse.headers["Location"];
    if (!uploadUrl)
      throw new Error("Failed to get resumable update URL");
    const uploadResponse = await this.request({
      url: uploadUrl,
      method: "PUT",
      headers: {
        "Content-Type": mimeType
      },
      body: content
    });
    return uploadResponse.json;
  }
  async getUserInfo() {
    const response = await this.request({
      url: "https://www.googleapis.com/oauth2/v3/userinfo",
      method: "GET"
    });
    return response.json;
  }
  async deleteFile(fileId) {
    const url = `https://www.googleapis.com/drive/v3/files/${fileId}`;
    await this.request({ url, method: "DELETE" });
  }
};

// sync/engine.ts
var import_obsidian4 = require("obsidian");

// ui/sync-view.ts
var import_obsidian3 = require("obsidian");
var VIEW_TYPE_SYNC_STATUS = "gdrive-sync-status-view";
var SyncStatusView = class extends import_obsidian3.ItemView {
  constructor(leaf) {
    super(leaf);
    this.stats = {
      totalFiles: 0,
      processed: 0,
      failed: 0,
      currentFile: "",
      status: "Idle",
      lastSync: "Never",
      errors: [],
      conflicts: []
    };
  }
  getViewType() {
    return VIEW_TYPE_SYNC_STATUS;
  }
  getDisplayText() {
    return "Google Drive Sync";
  }
  getIcon() {
    return "cloud";
  }
  async onOpen() {
    const plugin = this.app.plugins.getPlugin("tether");
    if (plugin && plugin.syncEngine) {
      this.stats = { ...plugin.syncEngine.stats };
    }
    this.render();
  }
  updateStats(newStats) {
    this.stats = { ...this.stats, ...newStats };
    this.render();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("gdrive-sync-view");
    container.createEl("h3", { text: "Sync Status" });
    const statsGrid = container.createDiv({ cls: "sync-stats-grid" });
    this.createStat(statsGrid, "Status", this.stats.status);
    this.createStat(statsGrid, "Progress", `${this.stats.processed} / ${this.stats.totalFiles}`);
    this.createStat(statsGrid, "Conflicts", this.stats.conflicts.length.toString(), this.stats.conflicts.length > 0 ? "text-warning" : "");
    this.createStat(statsGrid, "Failed", this.stats.failed.toString(), this.stats.failed > 0 ? "text-error" : "");
    if (this.stats.currentFile) {
      container.createEl("p", { text: `Currently: ${this.stats.currentFile}`, cls: "current-file-text" });
    }
    if (this.stats.conflicts.length > 0) {
      container.createEl("h4", { text: "\u{1F6A9} Conflicts (Needs Review)" });
      const conflictList = container.createDiv({ cls: "sync-conflict-list" });
      this.stats.conflicts.forEach((conflict) => {
        const item = conflictList.createDiv({ cls: "conflict-item" });
        const info = item.createDiv({ cls: "conflict-info" });
        info.createEl("b", { text: conflict.path.split("/").pop() || conflict.path });
        info.createEl("p", { text: `Original: ${conflict.originalPath}`, cls: "conflict-original-path" });
        const btnContainer = item.createDiv({ cls: "conflict-buttons" });
        const openBtn = btnContainer.createEl("button", { text: "Open", cls: "mod-cta conflict-open-btn" });
        openBtn.onClickEvent(async () => {
          try {
            const file = this.app.vault.getAbstractFileByPath(conflict.path);
            if (file instanceof import_obsidian3.TFile) {
              await this.app.workspace.getLeaf(true).openFile(file);
            } else if (conflict.path.startsWith(".obsidian/")) {
              new Notice("Cannot open hidden config files directly in the editor. Please use an external editor or a File Explorer plugin to view this file.");
            } else {
              await this.app.workspace.openLinkText(conflict.path, "", true);
            }
          } catch (e) {
            console.error("Failed to open conflict file", e);
            new Notice("Failed to open file: " + e.message);
          }
        });
        const delBtn = btnContainer.createEl("button", { text: "Delete", cls: "mod-warning conflict-del-btn" });
        delBtn.onClickEvent(async () => {
          if (confirm(`Are you sure you want to delete this conflict file?
${conflict.path}`)) {
            try {
              await this.app.vault.adapter.remove(conflict.path);
              this.stats.conflicts = this.stats.conflicts.filter((c) => c.path !== conflict.path);
              this.render();
              new Notice("Conflict file deleted.");
            } catch (e) {
              new Notice("Failed to delete file: " + e.message);
            }
          }
        });
      });
    }
    if (this.stats.errors.length > 0) {
      container.createEl("h4", { text: "Recent Errors" });
      const errorList = container.createDiv({ cls: "sync-error-list" });
      this.stats.errors.slice(-10).reverse().forEach((err) => {
        const item = errorList.createDiv({ cls: "error-item" });
        item.createEl("b", { text: err.path.split("/").pop() || err.path });
        item.createEl("p", { text: err.message });
      });
    }
  }
  createStat(parent, label, value, cls = "") {
    const stat = parent.createDiv({ cls: "sync-stat" });
    stat.createDiv({ text: label, cls: "stat-label" });
    stat.createDiv({ text: value, cls: "stat-value " + cls });
  }
};

// sync/engine.ts
var SyncEngine = class {
  constructor(app, client, stateManager, folderId, statusBarItem) {
    this.folderCache = /* @__PURE__ */ new Map();
    this.stats = {
      totalFiles: 0,
      processed: 0,
      failed: 0,
      currentFile: "",
      status: "Idle",
      lastSync: "",
      errors: [],
      conflicts: []
    };
    this.app = app;
    this.client = client;
    this.stateManager = stateManager;
    this.folderId = folderId;
    this.statusBarItem = statusBarItem;
  }
  updateStatus(text, partialStats) {
    this.statusBarItem.setText(`\u2601\uFE0F GDrive: ${text}`);
    this.stats.status = text;
    if (partialStats) {
      this.stats = { ...this.stats, ...partialStats };
    }
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_SYNC_STATUS);
    if (leaves.length > 0) {
      const view = leaves[0].view;
      if (typeof view.updateStats === "function") {
        view.updateStats(this.stats);
      }
    }
  }
  async sync() {
    var _a, _b;
    if (!this.folderId) {
      new import_obsidian4.Notice("Google Drive folder ID not set.");
      return;
    }
    try {
      this.stats.processed = 0;
      this.stats.failed = 0;
      this.stats.errors = [];
      this.folderCache.clear();
      this.updateStatus("Loading state...");
      await this.stateManager.load();
      const vaultName = this.app.vault.getName();
      this.updateStatus(`Locating vault root...`);
      const vaultRootDriveId = await this.ensureVaultRoot(vaultName);
      this.folderCache.set("", vaultRootDriveId);
      this.updateStatus("Fetching remote changes...");
      const remoteMap = await this.buildRemoteMap(vaultRootDriveId);
      this.updateStatus("Scanning local items...");
      const localPaths = await this.listAllLocalItems("");
      const localPathSet = new Set(localPaths);
      this.stats.totalFiles = localPaths.length;
      await this.handleRemoteDeletions(remoteMap);
      this.updateStatus("Checking for deletions...");
      const stateEntries = Object.entries(this.stateManager.state);
      for (const [path, entry] of stateEntries) {
        if (path === "__VAULT_ROOT__" || this.isExcluded(path))
          continue;
        if (!localPathSet.has(path)) {
          try {
            this.updateStatus(`Deleting remote: ${path}`);
            await this.client.deleteFile(entry.driveId);
            this.stateManager.remove(path);
            remoteMap.delete(path);
          } catch (e) {
            if (e.status === 404 || ((_a = e.message) == null ? void 0 : _a.includes("404"))) {
              this.stateManager.remove(path);
              remoteMap.delete(path);
            } else {
              console.error(`Failed to delete remote ${path}`, e);
              this.stats.failed++;
              this.stats.errors.push({ path, message: e.message });
            }
          }
        }
      }
      this.updateStatus("Pulling changes...");
      for (const [path, remoteFile] of remoteMap.entries()) {
        if (this.isExcluded(path))
          continue;
        try {
          this.stats.currentFile = path;
          await this.processRemoteFile(path, remoteFile);
        } catch (e) {
          console.error(`Failed to pull ${path}`, e);
          if (e.status === 404 || ((_b = e.message) == null ? void 0 : _b.includes("404"))) {
            this.stateManager.remove(path);
          } else {
            this.stats.failed++;
            this.stats.errors.push({ path, message: e.message });
          }
        }
        this.updateStatus(this.stats.status);
      }
      this.updateStatus("Pushing changes...");
      for (const path of localPaths) {
        this.stats.processed++;
        this.stats.currentFile = path;
        if (this.stats.processed % 5 === 0 || this.stats.processed === this.stats.totalFiles) {
          this.updateStatus(`Syncing ${this.stats.processed}/${this.stats.totalFiles}${this.stats.failed ? ` (${this.stats.failed} failed)` : ""}`);
        }
        try {
          await this.processLocalPath(path, vaultRootDriveId);
        } catch (e) {
          console.error(`Failed to push ${path}`, e);
          if (e.status === 404 || e.message.includes("404")) {
            this.stateManager.remove(path);
          } else {
            this.stats.failed++;
            this.stats.errors.push({ path, message: e.message });
          }
        }
        this.updateStatus(this.stats.status);
      }
      this.stats.lastSync = new Date().toLocaleTimeString();
      this.stats.currentFile = "";
      this.updateStatus("Idle");
      await this.stateManager.save();
      if (this.stats.failed > 0) {
        new import_obsidian4.Notice(`Sync complete with ${this.stats.failed} errors. Check sidebar.`);
      } else {
        new import_obsidian4.Notice("Sync complete successfully!");
      }
    } catch (error) {
      this.updateStatus("Failed");
      console.error("Critical sync failure", error);
      throw error;
    }
  }
  isExcluded(path) {
    return path.startsWith(".git/") || path === ".git" || path.startsWith(".trash/") || path === ".trash" || path === ".obsidian/gdrive-sync.json" || path.includes("/.git/");
  }
  async listAllLocalItems(folderPath) {
    const items = [];
    const result = await this.app.vault.adapter.list(folderPath);
    for (const file of result.files) {
      if (!this.isExcluded(file)) {
        items.push(file);
      }
    }
    for (const folder of result.folders) {
      if (!this.isExcluded(folder)) {
        items.push(folder);
        const subItems = await this.listAllLocalItems(folder);
        items.push(...subItems);
      }
    }
    return items;
  }
  async processLocalPath(path, vaultRootId) {
    const stat = await this.app.vault.adapter.stat(path);
    if (!stat)
      return;
    if (stat.type === "folder") {
      await this.ensureRemotePathByPath(path, vaultRootId);
      return;
    }
    const state = this.stateManager.get(path);
    const extension = path.includes(".") ? path.split(".").pop() || "" : "";
    const mimeType = this.getMimeType(extension);
    const fileName = path.split("/").pop() || path;
    if (!state) {
      const parentPath = path.includes("/") ? path.split("/").slice(0, -1).join("/") : "";
      const driveParentId = await this.ensureRemotePathByPath(parentPath, vaultRootId);
      const content = await this.app.vault.adapter.readBinary(path);
      const remoteFile = await this.client.uploadFile(fileName, driveParentId, content, mimeType);
      this.stateManager.set(path, {
        driveId: remoteFile.id,
        lastSyncedMtime: stat.mtime,
        remoteMtime: remoteFile.modifiedTime,
        etag: ""
      });
      await this.stateManager.save();
    } else if (stat.mtime > state.lastSyncedMtime) {
      const content = await this.app.vault.adapter.readBinary(path);
      const remoteFile = await this.client.updateFile(state.driveId, content, mimeType);
      this.stateManager.set(path, {
        ...state,
        lastSyncedMtime: stat.mtime,
        remoteMtime: remoteFile.modifiedTime
      });
      await this.stateManager.save();
    }
  }
  async ensureRemotePathByPath(path, vaultRootId) {
    if (!path || path === "." || path === "/")
      return vaultRootId;
    if (this.folderCache.has(path))
      return this.folderCache.get(path);
    const state = this.stateManager.get(path);
    if (state) {
      this.folderCache.set(path, state.driveId);
      return state.driveId;
    }
    const parts = path.split("/");
    const folderName = parts.pop() || "";
    const parentPath = parts.join("/");
    const parentDriveId = await this.ensureRemotePathByPath(parentPath, vaultRootId);
    const existingFolders = await this.client.listFolders(parentDriveId);
    const existing = existingFolders.find((f) => f.name.toLowerCase() === folderName.toLowerCase());
    if (existing) {
      this.stateManager.set(path, {
        driveId: existing.id,
        lastSyncedMtime: 0,
        remoteMtime: existing.modifiedTime,
        etag: ""
      });
      this.folderCache.set(path, existing.id);
      await this.stateManager.save();
      return existing.id;
    }
    const remoteFolder = await this.client.createFolder(folderName, parentDriveId);
    this.stateManager.set(path, {
      driveId: remoteFolder.id,
      lastSyncedMtime: 0,
      remoteMtime: remoteFolder.modifiedTime,
      etag: ""
    });
    this.folderCache.set(path, remoteFolder.id);
    await this.stateManager.save();
    return remoteFolder.id;
  }
  async buildRemoteMap(folderId, parentPath = "", depth = 0) {
    if (depth > 50)
      throw new Error("Maximum folder depth reached.");
    const map = /* @__PURE__ */ new Map();
    this.updateStatus(`Scanning Drive: ${parentPath || "root"}...`);
    try {
      const items = await this.client.listFiles(folderId);
      for (const item of items) {
        const path = parentPath ? `${parentPath}/${item.name}` : item.name;
        if (item.mimeType === "application/vnd.google-apps.folder") {
          map.set(path, item);
          const subMap = await this.buildRemoteMap(item.id, path, depth + 1);
          for (const [subPath, subFile] of subMap) {
            map.set(subPath, subFile);
          }
        } else {
          map.set(path, item);
        }
      }
    } catch (error) {
      console.error(`Failed to scan Drive folder ${folderId}`, error);
      throw error;
    }
    return map;
  }
  async ensureVaultRoot(name) {
    const stateKey = `__VAULT_ROOT__`;
    const state = this.stateManager.get(stateKey);
    if (state)
      return state.driveId;
    const folders = await this.client.listFolders(this.folderId);
    const existing = folders.find((f) => f.name.toLowerCase() === name.toLowerCase());
    if (existing) {
      const entry2 = { driveId: existing.id, lastSyncedMtime: 0, remoteMtime: existing.modifiedTime, etag: "" };
      this.stateManager.set(stateKey, entry2);
      await this.stateManager.save();
      return existing.id;
    }
    const newFolder = await this.client.createFolder(name, this.folderId);
    const entry = { driveId: newFolder.id, lastSyncedMtime: 0, remoteMtime: newFolder.modifiedTime, etag: "" };
    this.stateManager.set(stateKey, entry);
    await this.stateManager.save();
    return newFolder.id;
  }
  async processRemoteFile(path, remoteFile) {
    if (remoteFile.mimeType === "application/vnd.google-apps.folder") {
      await this.ensureLocalPath(path);
      const state2 = this.stateManager.get(path);
      this.stateManager.set(path, {
        driveId: remoteFile.id,
        lastSyncedMtime: state2 ? state2.lastSyncedMtime : 0,
        remoteMtime: remoteFile.modifiedTime,
        etag: ""
      });
      await this.stateManager.save();
      return;
    }
    const state = this.stateManager.get(path);
    const existsLocal = await this.app.vault.adapter.exists(path);
    if (!state) {
      if (existsLocal) {
        const stat = await this.app.vault.adapter.stat(path);
        if (path.startsWith(".obsidian/") && stat) {
          const remoteTime = new Date(remoteFile.modifiedTime).getTime();
          if (remoteTime > stat.mtime) {
            await this.download(path, remoteFile);
          } else {
            this.stateManager.set(path, {
              driveId: remoteFile.id,
              lastSyncedMtime: stat.mtime,
              remoteMtime: remoteFile.modifiedTime,
              etag: ""
            });
            await this.stateManager.save();
          }
        } else {
          await this.handleConflict(path, remoteFile);
        }
      } else {
        await this.download(path, remoteFile);
      }
    } else if (remoteFile.modifiedTime !== state.remoteMtime) {
      const stat = await this.app.vault.adapter.stat(path);
      if (stat && stat.mtime > state.lastSyncedMtime) {
        if (path.startsWith(".obsidian/")) {
          const remoteTime = new Date(remoteFile.modifiedTime).getTime();
          if (remoteTime > stat.mtime) {
            await this.download(path, remoteFile);
          } else {
            this.stateManager.set(path, {
              ...state,
              remoteMtime: remoteFile.modifiedTime
            });
            await this.stateManager.save();
          }
        } else {
          await this.handleConflict(path, remoteFile);
        }
      } else {
        await this.download(path, remoteFile);
      }
    }
  }
  async handleRemoteDeletions(remoteMap) {
    const stateEntries = Object.entries(this.stateManager.state);
    const sortedEntries = stateEntries.filter(([path]) => path !== "__VAULT_ROOT__" && !this.isExcluded(path)).sort((a, b) => b[0].length - a[0].length);
    for (const [path, entry] of sortedEntries) {
      if (!remoteMap.has(path)) {
        try {
          if (await this.app.vault.adapter.exists(path)) {
            this.updateStatus(`Deleting local: ${path}`);
            const stat = await this.app.vault.adapter.stat(path);
            if ((stat == null ? void 0 : stat.type) === "folder") {
              await this.app.vault.adapter.rmdir(path, false).catch(async (err) => {
                if (!path.startsWith(".obsidian/")) {
                  await this.app.vault.adapter.rmdir(path, true);
                }
              });
            } else {
              await this.app.vault.adapter.remove(path);
            }
          }
          this.stateManager.remove(path);
        } catch (e) {
          console.error(`Failed to delete local ${path}`, e);
          this.stats.failed++;
          this.stats.errors.push({ path, message: e.message });
        }
      }
    }
  }
  async download(path, remoteFile) {
    const content = await this.client.downloadFile(remoteFile.id);
    const parts = path.split("/");
    if (parts.length > 1) {
      const folderPath = parts.slice(0, -1).join("/");
      await this.ensureLocalPath(folderPath);
    }
    await this.app.vault.adapter.writeBinary(path, content);
    const stat = await this.app.vault.adapter.stat(path);
    this.stateManager.set(path, {
      driveId: remoteFile.id,
      lastSyncedMtime: stat ? stat.mtime : Date.now(),
      remoteMtime: remoteFile.modifiedTime,
      etag: ""
    });
    await this.stateManager.save();
  }
  async ensureLocalPath(path) {
    if (!path || path === ".")
      return;
    if (await this.app.vault.adapter.exists(path))
      return;
    const parts = path.split("/");
    const parent = parts.slice(0, -1).join("/");
    if (parent)
      await this.ensureLocalPath(parent);
    try {
      await this.app.vault.adapter.mkdir(path);
    } catch (e) {
      const msg = (e.message || e.toString()).toLowerCase();
      if (!msg.includes("already exists")) {
        throw e;
      }
    }
  }
  async handleConflict(path, remoteFile) {
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const lastDotIndex = path.lastIndexOf(".");
    const conflictPath = lastDotIndex !== -1 ? path.slice(0, lastDotIndex) + ` (conflict ${timestamp})` + path.slice(lastDotIndex) : `${path} (conflict ${timestamp})`;
    const content = await this.client.downloadFile(remoteFile.id);
    const parts = conflictPath.split("/");
    if (parts.length > 1) {
      const folderPath = parts.slice(0, -1).join("/");
      await this.ensureLocalPath(folderPath);
    }
    await this.app.vault.adapter.writeBinary(conflictPath, content);
    new import_obsidian4.Notice(`Conflict detected for ${path}. Kept both versions.`);
    this.stats.conflicts.push({
      path: conflictPath,
      originalPath: path,
      timestamp
    });
    const stat = await this.app.vault.adapter.stat(conflictPath);
    this.stateManager.set(conflictPath, {
      driveId: remoteFile.id,
      lastSyncedMtime: stat ? stat.mtime : Date.now(),
      remoteMtime: remoteFile.modifiedTime,
      etag: ""
    });
    await this.stateManager.save();
  }
  getMimeType(extension) {
    const mimes = {
      "md": "text/markdown",
      "txt": "text/plain",
      "png": "image/png",
      "jpg": "image/jpeg",
      "jpeg": "image/jpeg",
      "gif": "image/gif",
      "pdf": "application/pdf",
      "mp4": "video/mp4",
      "zip": "application/zip"
    };
    return mimes[extension] || "application/octet-stream";
  }
};

// ui/folder-modal.ts
var import_obsidian5 = require("obsidian");
var FolderSuggestModal = class extends import_obsidian5.Modal {
  constructor(app, client, onSelect) {
    super(app);
    this.currentFolderId = "root";
    this.currentFolderName = "My Drive";
    this.pathStack = [];
    this.client = client;
    this.onSelect = onSelect;
  }
  async onOpen() {
    await this.render();
  }
  async render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Select Google Drive Folder" });
    const navPath = this.pathStack.map((f) => f.name).join(" > ");
    contentEl.createEl("div", { text: `Path: My Drive ${navPath ? "> " + navPath : ""}`, cls: "gdrive-folder-path" });
    const listEl = contentEl.createDiv({ cls: "gdrive-folder-list" });
    listEl.createEl("p", { text: "Loading folders..." });
    try {
      const folders = await this.client.listFolders(this.currentFolderId);
      listEl.empty();
      new import_obsidian5.Setting(listEl).setName(`\u{1F3AF} Select "${this.currentFolderName}"`).setDesc("Click to use this folder for syncing.").addButton((btn) => btn.setButtonText("Select This Folder").setCta().onClick(() => {
        this.onSelect({ id: this.currentFolderId, name: this.currentFolderName, mimeType: "", modifiedTime: "" });
        this.close();
      }));
      if (this.pathStack.length > 0) {
        new import_obsidian5.Setting(listEl).setName("\u2B05 Back").addButton((btn) => btn.setButtonText("Go Up").onClick(async () => {
          const parent = this.pathStack.pop();
          if (this.pathStack.length === 0) {
            this.currentFolderId = "root";
            this.currentFolderName = "My Drive";
          } else {
            const prev = this.pathStack[this.pathStack.length - 1];
            this.currentFolderId = prev.id;
            this.currentFolderName = prev.name;
          }
          await this.render();
        }));
      }
      new import_obsidian5.Setting(listEl).setName("++ Create New Sub-Folder ++").addButton((btn) => btn.setButtonText("Create").onClick(() => {
        new CreateFolderModal(this.app, this.client, this.currentFolderId, async (newFolder) => {
          await this.render();
        }).open();
      }));
      if (folders.length === 0) {
        listEl.createEl("p", { text: "No sub-folders found here.", style: "opacity: 0.6; text-align: center; margin: 20px 0;" });
      }
      folders.forEach((folder) => {
        new import_obsidian5.Setting(listEl).setName(`\u{1F4C1} ${folder.name}`).addButton((btn) => btn.setButtonText("Open").onClick(async () => {
          this.pathStack.push({ id: folder.id, name: folder.name });
          this.currentFolderId = folder.id;
          this.currentFolderName = folder.name;
          await this.render();
        }));
      });
    } catch (error) {
      listEl.empty();
      listEl.createEl("p", { text: "Failed to fetch folders: " + error.message });
      console.error("Folder fetch failed", error);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var CreateFolderModal = class extends import_obsidian5.Modal {
  constructor(app, client, parentId, onCreated) {
    super(app);
    this.folderName = "";
    this.client = client;
    this.parentId = parentId;
    this.onCreated = onCreated;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Create New Sub-Folder" });
    new import_obsidian5.Setting(contentEl).setName("Folder Name").addText((text) => text.setPlaceholder("Enter folder name...").onChange((value) => this.folderName = value));
    new import_obsidian5.Setting(contentEl).addButton((btn) => btn.setButtonText("Create").setCta().onClick(async () => {
      if (!this.folderName) {
        new import_obsidian5.Notice("Please enter a folder name");
        return;
      }
      try {
        const folder = await this.client.createFolder(this.folderName, this.parentId);
        new import_obsidian5.Notice(`Folder "${this.folderName}" created`);
        this.onCreated(folder);
        this.close();
      } catch (error) {
        new import_obsidian5.Notice("Failed to create folder: " + error.message);
      }
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// ui/setup-guide.ts
var import_obsidian6 = require("obsidian");
var SETUP_GUIDE_IMAGE_BASE_URL = "https://raw.githubusercontent.com/Llewellyn500/obsidian-tether/main/images";
function getSetupGuideImageUrl(imageName) {
  return `${SETUP_GUIDE_IMAGE_BASE_URL}/${imageName}.png`;
}
var SetupGuideModal = class extends import_obsidian6.Modal {
  constructor(app) {
    super(app);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("gdrive-setup-modal");
    contentEl.createEl("h2", { text: "\u{1F680} Tether: Full Setup Guide" });
    const subtitle = contentEl.createEl("p", {
      text: "Follow these steps to configure your Google Cloud project. This ensures full vault sync (including hidden folders) works perfectly."
    });
    subtitle.setAttr("style", "opacity: 0.8; margin-bottom: 16px;");
    const stepsContainer = contentEl.createDiv({ cls: "setup-steps-scroll" });
    stepsContainer.setAttr("style", "max-height: 70vh; overflow-y: auto; padding-right: 10px; margin-bottom: 20px;");
    const steps = [
      { text: "Go to Google Cloud Console", image: "step-1" },
      { text: 'Click "Select a project"', image: "step-2" },
      { text: 'Click "New project"', image: "step-3" },
      { text: 'In the project name field, type "Tether-Sync"', image: "step-4" },
      { text: 'Click "Create"', image: "step-5" },
      { text: 'Click "APIs & Services"', image: "step-6" },
      { text: 'Click "Library"', image: "step-7" },
      { text: 'Click the "Search for APIs & Services" field.', image: "step-8" },
      { text: 'Type "Google drive"' },
      { text: 'Click "google drive api"', image: "step-10" },
      { text: 'Click "Google Drive API"', image: "step-11" },
      { text: 'Click "Enable"', image: "step-12" },
      { text: 'Click "OAuth consent screen"', image: "step-13" },
      { text: 'Click "Get started"', image: "step-14" },
      { text: 'Click the "App name" field.', image: "step-15" },
      { text: 'Type "Tether-Sync"' },
      { text: "Click User Support email.", image: "step-17" },
      { text: "Click your email address from the dropdown." },
      { text: 'Click "External"', image: "step-19" },
      { text: `Pick the developer's "Email address" (Developer contact info)`, image: "step-20" },
      { text: 'Click the "I agree to the Google API Services: User Data Policy." field.' },
      { text: 'Click "Create"', image: "step-22" },
      { text: 'Click "Data Access"', image: "step-23" },
      { text: 'Click "Add or remove scopes"', image: "step-24" },
      {
        text: "Copy the scope string below:",
        codeBlock: "https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.metadata.readonly openid email"
      },
      { text: 'Paste the string in the "Manually add scopes" field.', image: "step-26" },
      { text: 'Click "Add to table"', image: "step-27" },
      { text: 'Click "Update"', image: "step-28" },
      { text: 'Click "Save"', image: "step-29" },
      { text: 'Click "Audience"', image: "step-30" },
      { text: 'Click "Add users"', image: "step-31" },
      { text: "Add your email as a user." },
      { text: 'Click "Clients"', image: "step-33" },
      { text: 'Click "Create client"', image: "step-34" },
      { text: 'Choose "Web application" as the application type.', image: "step-35" },
      { text: 'Type "Tether Sync" in the "Name" field.', image: "step-36" },
      {
        text: "Copy the redirect URI below:",
        codeBlock: "https://obsidian.md"
      },
      { text: 'Click the "Add URI" icon.', image: "step-38" },
      { text: 'Paste the redirect URI in the "URIs 1" field.', image: "step-39" },
      { text: 'Click "Create"' },
      { text: "Copy the Client ID and paste it in Tether's settings." },
      { text: "Copy the Client Secret and paste it in Tether's settings.", image: "step-42" }
    ];
    steps.forEach((step, index) => {
      const stepDiv = stepsContainer.createDiv({ cls: "setup-step" });
      stepDiv.setAttr("style", "margin-bottom: 24px; border-bottom: 1px solid var(--background-modifier-border); padding-bottom: 20px;");
      const headerEl = stepDiv.createEl("div");
      headerEl.setAttr("style", "display: flex; align-items: baseline; gap: 8px; margin-bottom: 6px;");
      const badge = headerEl.createEl("span", { text: `${index + 1}` });
      badge.setAttr("style", "display: inline-flex; align-items: center; justify-content: center; min-width: 28px; height: 28px; border-radius: 50%; background: var(--interactive-accent); color: var(--text-on-accent); font-weight: 700; font-size: 13px; flex-shrink: 0;");
      const textEl = headerEl.createEl("span", { text: step.text });
      textEl.setAttr("style", "font-size: 15px; line-height: 1.5;");
      if (step.codeBlock) {
        const codeWrapper = stepDiv.createEl("div");
        codeWrapper.setAttr("style", "position: relative; margin-top: 8px; border-radius: 6px; overflow: hidden;");
        const code = codeWrapper.createEl("code", { text: step.codeBlock });
        code.setAttr("style", "display: block; background: var(--code-background); padding: 12px 14px; color: var(--code-normal); font-size: 13px; word-break: break-all; border-radius: 6px; border: 1px solid var(--background-modifier-border); font-family: var(--font-monospace); user-select: all; cursor: text;");
      }
      if (step.image) {
        const img = stepDiv.createEl("img");
        img.setAttr("src", getSetupGuideImageUrl(step.image));
        img.setAttr("alt", `Screenshot for Step ${index + 1}`);
        img.setAttr("loading", "lazy");
        img.setAttr("style", "max-width: 100%; border: 1px solid var(--background-modifier-border); border-radius: 6px; display: block; margin-top: 10px; min-height: 40px; background: var(--background-secondary);");
      }
    });
    const finalStep = stepsContainer.createDiv({ cls: "setup-step" });
    finalStep.setAttr("style", "margin-bottom: 24px; padding-bottom: 20px;");
    const finalHeader = finalStep.createEl("h3", { text: "\u{1F510} Final Step: Authentication" });
    finalHeader.setAttr("style", "margin-top: 8px; margin-bottom: 12px;");
    const loginSteps = [
      'In Obsidian settings for Tether, click "Open Login Page".',
      "Log in with your Google account.",
      "You will be redirected to obsidian.md. Copy the entire URL from your browser bar.",
      'Paste that URL into the "Authorization Code" box in Obsidian and click Verify Code.'
    ];
    const list = finalStep.createEl("ol");
    list.setAttr("style", "padding-left: 22px; line-height: 1.8;");
    loginSteps.forEach((text) => {
      list.createEl("li", { text });
    });
    const readyBanner = contentEl.createEl("div");
    readyBanner.setAttr("style", "text-align: center; padding: 12px; margin-bottom: 8px; border-radius: 8px; background: var(--background-secondary);");
    readyBanner.createEl("span", { text: "\u{1F389} You are ready to go!" }).setAttr("style", "font-weight: 700; font-size: 16px;");
    const btnContainer = contentEl.createDiv({ cls: "modal-button-container" });
    btnContainer.createEl("button", { text: "Got it, let's go!", cls: "mod-cta" }).onClickEvent(() => this.close());
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
init_oauth();
var DEFAULT_SETTINGS = {
  accessToken: "",
  refreshToken: "",
  clientId: "",
  clientSecret: "",
  codeVerifier: "",
  userEmail: "",
  folderId: "",
  folderName: "",
  syncInterval: 15,
  syncOnStartup: true
};
var GoogleDriveSyncPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.isSyncing = false;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_SYNC_STATUS, (leaf) => new SyncStatusView(leaf));
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.setText("\u2601\uFE0F GDrive: Idle");
    this.statusBarItem.onClickEvent(() => this.activateView());
    this.stateManager = new StateManager(this);
    await this.stateManager.load();
    if (this.settings.accessToken) {
      this.initializeClient();
      this.setupSyncEngine();
      if (this.settings.syncOnStartup && this.settings.folderId) {
        setTimeout(() => {
          new import_obsidian7.Notice("Google Drive: Checking for updates...");
          this.backgroundSync();
        }, 5e3);
      }
    }
    const ribbonIconEl = this.addRibbonIcon("cloud", "Sync with Google Drive", (evt) => {
      this.manualSync();
    });
    ribbonIconEl.addClass("gdrive-sync-ribbon-icon");
    this.addCommand({
      id: "sync-google-drive",
      name: "Sync with Google Drive",
      callback: () => this.manualSync()
    });
    this.addCommand({
      id: "open-gdrive-sync-status",
      name: "Open Sync Status Sidebar",
      callback: () => this.activateView()
    });
    this.addSettingTab(new GoogleDriveSyncSettingTab(this.app, this));
    if (this.settings.syncInterval > 0) {
      this.registerInterval(window.setInterval(() => this.backgroundSync(), this.settings.syncInterval * 60 * 1e3));
    }
    console.log("Google Drive Sync plugin loaded");
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_SYNC_STATUS);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (!leaf)
        return;
      await leaf.setViewState({ type: VIEW_TYPE_SYNC_STATUS, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  async onunload() {
    console.log("Google Drive Sync plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  initializeClient() {
    this.client = new GoogleDriveClient(this.settings.accessToken, async (tokens) => {
      this.settings.accessToken = tokens.access_token;
      if (tokens.refresh_token)
        this.settings.refreshToken = tokens.refresh_token;
      await this.saveSettings();
    }, {
      refreshToken: this.settings.refreshToken,
      clientId: this.settings.clientId,
      clientSecret: this.settings.clientSecret
    });
  }
  setupSyncEngine() {
    if (!this.settings.folderId)
      return;
    if (!this.syncEngine) {
      this.syncEngine = new SyncEngine(this.app, this.client, this.stateManager, this.settings.folderId, this.statusBarItem);
    } else {
      this.syncEngine.client = this.client;
      this.syncEngine.folderId = this.settings.folderId;
    }
  }
  async saveSettings() {
    var _a;
    const oldFolderId = (_a = await this.loadData()) == null ? void 0 : _a.folderId;
    await this.saveData(this.settings);
    if (this.settings.folderId && this.settings.folderId !== oldFolderId) {
      new import_obsidian7.Notice("Sync folder changed. Resetting local sync state...");
      await this.app.vault.adapter.remove(".obsidian/gdrive-sync.json").catch(() => {
      });
      if (this.stateManager)
        this.stateManager.state = {};
    }
    if (this.settings.accessToken) {
      this.initializeClient();
      this.setupSyncEngine();
    }
  }
  async manualSync() {
    if (this.isSyncing) {
      new import_obsidian7.Notice("Sync is already in progress.");
      return;
    }
    if (!this.settings.accessToken) {
      new import_obsidian7.Notice("Please log in to Google Drive first in settings.");
      return;
    }
    if (!this.settings.folderId) {
      new import_obsidian7.Notice("Please select a Google Drive folder in settings.");
      return;
    }
    this.isSyncing = true;
    await this.activateView();
    this.setupSyncEngine();
    new import_obsidian7.Notice("Starting Tether Sync...");
    try {
      await this.syncEngine.sync();
    } catch (error) {
      console.error("Sync failed", error);
      new import_obsidian7.Notice(`Sync failed: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      this.isSyncing = false;
    }
  }
  async backgroundSync() {
    if (this.isSyncing || !this.settings.accessToken || !this.settings.folderId)
      return;
    this.isSyncing = true;
    this.setupSyncEngine();
    try {
      await this.syncEngine.sync();
    } catch (error) {
      console.error("Background sync failed", error);
    } finally {
      this.isSyncing = false;
    }
  }
  async startLogin() {
    const verifier = await OAuthManager.generateCodeVerifier();
    this.settings.codeVerifier = verifier;
    await this.saveSettings();
    const challenge = await OAuthManager.generateCodeChallenge(verifier);
    const url = await OAuthManager.getAuthUrl(this.settings.clientId, challenge);
    window.open(url, "_blank");
  }
  async finalizeLogin(input) {
    try {
      let code = input;
      if (input.includes("code=")) {
        const url = input.replace("#", "?");
        const urlParams = new URLSearchParams(url.split("?")[1]);
        code = urlParams.get("code") || input;
      }
      code = decodeURIComponent(code);
      const tokens = await OAuthManager.exchangeCodeForToken(code, this.settings.codeVerifier, this.settings.clientId, this.settings.clientSecret);
      this.settings.accessToken = tokens.access_token;
      this.settings.refreshToken = tokens.refresh_token;
      const client = new GoogleDriveClient(tokens.access_token);
      const userInfo = await client.getUserInfo();
      this.settings.userEmail = userInfo.email;
      await this.saveSettings();
      new import_obsidian7.Notice(`Successfully logged in as ${userInfo.email}!`);
    } catch (error) {
      console.error("Login failed", error);
      new import_obsidian7.Notice("Login failed: " + (error instanceof Error ? error.message : String(error)));
    }
  }
};
var GoogleDriveSyncSettingTab = class extends import_obsidian7.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.authCode = "";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Tether: Setup Wizard" });
    containerEl.createEl("p", { text: "Created by Llewellyn Paintsil", cls: "tether-author-credit" });
    const step1 = containerEl.createEl("div", { cls: "gdrive-setup-step" });
    step1.createEl("h3", { text: "Step 1: API Credentials" });
    const hasKeys = this.plugin.settings.clientId && this.plugin.settings.clientSecret;
    if (hasKeys) {
      new import_obsidian7.Setting(step1).setName("Keys Saved \u2713").setDesc("Your Client ID and Secret are configured.").addButton((btn) => btn.setButtonText("Edit Keys").onClick(() => {
        this.plugin.settings.clientId = "";
        this.plugin.settings.clientSecret = "";
        this.display();
      }));
    } else {
      new import_obsidian7.Setting(step1).setName("Setup Guide").setDesc("First, follow this guide to get your keys.").addButton((button) => button.setButtonText("Open Guide").onClick(() => new SetupGuideModal(this.app).open()));
      new import_obsidian7.Setting(step1).setName("Client ID").addText((text) => text.setPlaceholder("Enter Client ID").setValue(this.plugin.settings.clientId).onChange(async (value) => {
        this.plugin.settings.clientId = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian7.Setting(step1).setName("Client Secret").addText((text) => text.setPlaceholder("Enter Client Secret").setValue(this.plugin.settings.clientSecret).onChange(async (value) => {
        this.plugin.settings.clientSecret = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian7.Setting(step1).addButton((btn) => btn.setButtonText("Continue").setCta().onClick(() => this.display()));
      return;
    }
    const step2 = containerEl.createEl("div", { cls: "gdrive-setup-step" });
    step2.createEl("h3", { text: "Step 2: Log in" });
    const isLoggedIn = !!this.plugin.settings.accessToken;
    if (isLoggedIn) {
      new import_obsidian7.Setting(step2).setName("Logged in \u2713").setDesc(`Account: ${this.plugin.settings.userEmail}`).addButton((btn) => btn.setButtonText("Log Out").onClick(async () => {
        this.plugin.settings.accessToken = "";
        this.plugin.settings.refreshToken = "";
        this.plugin.settings.userEmail = "";
        await this.plugin.saveSettings();
        this.display();
      }));
    } else {
      new import_obsidian7.Setting(step2).setName("Authorize Plugin").setDesc("Click to open Google login in your browser.").addButton((btn) => btn.setButtonText("Open Login Page").setCta().onClick(() => this.plugin.startLogin()));
      new import_obsidian7.Setting(step2).setName("Authorization Code").setDesc('After logging in, copy the "code=" part from the URL and paste it here.').addText((text) => text.setPlaceholder("Paste code here...").onChange((value) => this.authCode = value)).addButton((btn) => btn.setButtonText("Verify Code").onClick(async () => {
        if (!this.authCode) {
          new import_obsidian7.Notice("Please paste the code first.");
          return;
        }
        await this.plugin.finalizeLogin(this.authCode);
        this.display();
      }));
      return;
    }
    const step3 = containerEl.createEl("div", { cls: "gdrive-setup-step" });
    step3.createEl("h3", { text: "Step 3: Choose Folder" });
    const hasFolder = !!this.plugin.settings.folderId;
    new import_obsidian7.Setting(step3).setName(hasFolder ? "Folder Selected \u2713" : "Select Sync Folder").setDesc(hasFolder ? `Syncing with: ${this.plugin.settings.folderName}` : "Choose where to sync your notes.").addButton((btn) => {
      btn.setButtonText(hasFolder ? "Change Folder" : "Select Folder");
      if (!hasFolder)
        btn.setCta();
      btn.onClick(() => {
        new FolderSuggestModal(this.app, this.plugin.client, async (folder) => {
          this.plugin.settings.folderId = folder.id;
          this.plugin.settings.folderName = folder.name;
          await this.plugin.saveSettings();
          this.display();
          new import_obsidian7.Notice(`Sync folder set to ${folder.name}.`);
          this.plugin.manualSync();
        }).open();
      });
    });
    if (!hasFolder)
      return;
    const step4 = containerEl.createEl("div", { cls: "gdrive-setup-step" });
    step4.createEl("h3", { text: "Step 4: Sync Settings" });
    new import_obsidian7.Setting(step4).setName("Sync on Startup").setDesc("Automatically check for changes when Obsidian opens.").addToggle((toggle) => toggle.setValue(this.plugin.settings.syncOnStartup).onChange(async (value) => {
      this.plugin.settings.syncOnStartup = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian7.Setting(step4).setName("Sync Interval (minutes)").setDesc("Minutes between automatic syncs (0 to disable).").addText((text) => text.setPlaceholder("15").setValue(this.plugin.settings.syncInterval.toString()).onChange(async (value) => {
      this.plugin.settings.syncInterval = parseInt(value) || 0;
      await this.plugin.saveSettings();
    }));
    new import_obsidian7.Setting(step4).setName("Manual Sync").setDesc("Trigger a sync immediately.").addButton((btn) => btn.setButtonText("Sync Now").onClick(() => this.plugin.manualSync()));
  }
};
module.exports = __toCommonJS(main_exports);
